security:
    encoders:
        Dev\ApiBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            logout:       true
            anonymous:    ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/profile$, role: IS_AUTHENTICATED_FULLY}
            #- { path: ^/users$, role: ROLE_ADMIN }


